general.import = ["~/.config/alacritty/colors/colors.toml", "~/.config/alacritty/fonts.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.7
  [window.padding]
  x = 24
  y = 24
  [window.dimensions]
  columns = 80
  lines = 35

[scrolling]
history = 1_000
multiplier = 3


[cursor]
style = "Underline"
vi_mode_style = "Underline"