general.import = ["~/.config/alacritty/colors/colors.toml", "~/.config/alacritty/fonts.toml"]

general.live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "full"
opacity = 0.7
  [window.padding]
  x = 15
  y = 15
  [window.dimensions]
  columns = 80
  lines = 30



[scrolling]
history = 1_000
multiplier = 3


[cursor]
style = "Underline"
vi_mode_style = "Underline"