[colors.primary]
background = "#1a1b26"  # Slightly darker, richer background
foreground = "#e0e9ff"  # Brighter foreground for better contrast
dim_foreground = "#a9b1d6"  # Adjusted dim foreground
bright_foreground = "#f0f8ff"  # Even brighter foreground

[colors.cursor]
text = "#1a1b26"  # Matching the new background
cursor = "#bb9af7"  # Purple cursor for better visibility

[colors.vi_mode_cursor]
text = "#1a1b26"  # Matching the new background
cursor = "#7aa2f7"  # Blue vi mode cursor

[colors.search.matches]
foreground = "#1a1b26"  # Matching the new background
background = "#7aa2f7"  # Blue background for search matches

[colors.search.focused_match]
foreground = "#1a1b26"  # Matching the new background
background = "#7dcfff"  # Cyan background for focused match

[colors.footer_bar]
foreground = "#1a1b26"  # Matching the new background
background = "#7aa2f7"  # Blue background for footer

[colors.hints.start]
foreground = "#1a1b26"  # Matching the new background
background = "#e0af68"  # Orange background for hints

[colors.hints.end]
foreground = "#1a1b26"  # Matching the new background
background = "#7aa2f7"  # Blue background for hint ends

[colors.selection]
text = "#1a1b26"  # Matching the new background
background = "#515c7e"  # Subdued selection background

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"

[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

[colors.dim]
black = "#2a2b3d"
red = "#d5667b"
green = "#8ab85c"
yellow = "#c29a5b"
blue = "#6a8bd9"
magenta = "#9879c9"
cyan = "#3b8694"
white = "#666b85"

[[colors.indexed_colors]]
index = 16
color = "#ff9e64"

[[colors.indexed_colors]]
index = 17
color = "#db4b4b"