[colors.primary]
background = "0x0f1117"
foreground = "0xc0caf5"

[colors.normal]
black =   "0x24283b"
red =     "0xf7768e"
green =   "0x9ece6a"
yellow =  "0xe0af68"
blue =    "0x7aa2f7"
magenta = "0xbb9af7"
cyan =    "0x7dcfff"
white =   "0xa9b1d6"

[colors.bright]
black =   "0x414868"
red =     "0xff7a93"
green =   "0x9ece6a"
yellow =  "0xffc777"
blue =    "0x89ddff"
magenta = "0xc0caf5"
cyan =    "0xb4f9f8"
white =   "0xc0caf5"

[colors.cursor]
text = "CellBackground"
cursor = "0x89ddff"

[colors.selection]
text = "CellForeground"
background = "0x33467c"