[font]
size = 10

  [font.normal]
  family = "JetBrainsMono Nerd Font"

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.italic]
  family = "JetBrainsMono Nerd Font"

  [font.offset]
  x = 0
  y = 0

  [font.glyph_offset]
  x = 0
  y = 0