[font]
size = 11
  [font.normal]
  family = "Iosevka Nerd Font"
  style = "Regular"
  [font.bold]
  family = "Iosevka Nerd Font"
  style = "Bold"
  [font.italic]
  family = "Iosevka Nerd Font"
  style = "Italic"
  [font.offset]
  y = 0
  [font.glyph_offset]
  y = 0