#!/usr/bin/env bash

# sysfetch
# Thanks to gh0stzk for his sysinfo script
# Modified by Evrenos https://github.com/Evren-os/hyprblaze

# color escapes
CBK=$(tput setaf 0)
CRE=$(tput setaf 1)
CGR=$(tput setaf 2)
CYE=$(tput setaf 3)
CBL=$(tput setaf 4)

CMA=$(tput setaf 5)
CCY=$(tput setaf 6)
CWH=$(tput setaf 7)
CBD=$(tput bold)
CNC=$(tput sgr0)

#█▓▒░ progress bar
draw() {
  FULL=━
  EMPTY=━
  out=
  perc=$1
  size=$2
  inc=$(( perc * size / 100 ))
  color=34
  color2=31
  for v in $(seq 0 $(( size - 1 ))); do
    [ "$v" -le "$inc" ] && out="${out}${CMA}${FULL}" || out="${out}${CWH}${EMPTY}"
  done
  printf "%b" "$out"
}

#█▓▒░ populate vals
i=1
c=$(printf "\e[0m\e[31m░▒▓")
while [ $i -le 6 ];do
  c=${c}$(printf "\e[%dm\e[%dm█▓▒░" "$((i+41))" "$((i+30))")
  i=$((i+1))
done
COLORBAR=${c}$(printf "\e[37m█\e[0m▒░")


name=$USER
host=$(uname -n)
distro=$(uname -o | awk -F '"' '/PRETTY_NAME/ { print $2 }' /etc/os-release)
wm=$(xprop -id "$(xprop -root -notype | awk '$1=="_NET_SUPPORTING_WM_CHECK:"{print $5}')" -notype -f _NET_WM_NAME 8t | grep "WM_NAME" | cut -f2 -d \")
storage=$(df -h --output=used / | awk 'NR == 2 { print $1 }')
term=$(ps -o sid= -p "$$" | xargs ps -o ppid= -p | xargs ps -o comm= -p)
uptm=$(uptime -p | sed -e 's/hour/hr/' -e 's/hours/hrs/' -e 's/minutes/mins/' -e 's/minute/min/' -e 's/up //')

c_lvl=$(printf "%.0f" "$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')")
CPU=$(printf "%-4s\em%-5s%-25s \n" "${CGR}cpu${CNC} " "$c_lvl%" "$(draw "$c_lvl" 14)")
ram_lvl=$(free | awk '/Mem:/ {print int($3/$2 * 100.0)}')
RAM=$(printf "%-4s\em%-5s%-25s \n" "${CYE}ram${CNC} " "$ram_lvl%" "$(draw "$ram_lvl" 14)")
disk_lvl=$(df -h | grep '/$' | tr -s ' ' | cut -d ' ' -f5 | sed 's/%//')
DISK=$(printf "%-4s\em%-5s%-25s \n" "${CCY}disk${CNC} " "$disk_lvl%" "$(draw "$disk_lvl" 14)")

# Calculate OS age
install_date=$(ls -lct /etc | tail -1 | awk '{print $6, $7, $8}')
current_date=$(date +%s)
install_date_seconds=$(date -d "$install_date" +%s)
os_age=$((($current_date - $install_date_seconds) / 86400))

#Cleanup first
clear

# Ascii art arms
cat <<EOF
$CBD                  $CBL.
                 $CBL/ $CMA\\
                $CBL/   $CMA\\
               $CBL/^.   $CMA\\
              $CBL/  .$CWH-$CMA.  \\
             $CBL/  (   $CMA) _\\
            $CBL/ _.~   $CMA~._^\\
           $CBL/.^         $CMA^.\\
EOF

printf "\e[0m\n    %s\e[0m\n\n" "$COLORBAR"

# greetings
printf "%s\n" "             Hi $CRE$CBD$name$CNC"
printf "%s\n" "       Welcome to $CGR$CBD$host$CNC"
printf "%s\n\n" "           up $CCY$CBD$uptm$CNC"

# environment
printf "%s\n" "$CRE         distro ⚡ $CNC$distro"
printf "%s\n" "$CBL         kernel ⚡ $CNC$(uname -r)"
printf "%s\n" "$CGR          shell ⚡ $CNC${SHELL##*/}"
printf "%s\n" "$CYE           term ⚡ $CNC${term}"
printf "%s\n" "$CCY             wm ⚡ $CNC${wm}"
printf "%s\n" "$CBL           disk ⚡ $CNC${storage} used"
printf "%s\n" "$CMA            age ⚡ $CNC${os_age} days"
printf " %s\n" "$CNC"

printf "        %s\n        %s\n       %s\e[0m\n" "$CPU" "$RAM" "$DISK"

# hide the cursor and wait for user input
tput civis
read -n 1

# give the cursor back
tput cnorm